name: gap_o_eat
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

# PACKAGES
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8


#END
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

  #utilities
  flutter_native_splash: ^2.4.6

flutter:


  uses-material-design: true
# --------ASSETS----------------
assets:
  - assets/logo/



#------------FONTS------------

fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800

  

