name: gap_o_eat
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

# PACKAGES
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.0+3
  iconsax: ^0.0.8
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  connectivity_plus: ^6.1.3
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  dio: ^5.8.0+1
  crypto: ^3.0.6
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_branch_sdk: ^8.5.0
  flutter_stripe: ^11.5.0
  flutter_native_splash: ^2.4.6

#END
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# --------ASSETS----------------
assets:
  - assets/logo/
  - assets/images/

#------------FONTS------------
fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito-Light.ttf
        weight: 300
      - asset: assets/fonts/Nunito-Regular.ttf
        weight: 400
      - asset: assets/fonts/Nunito-Italic.ttf
        style: italic
      - asset: assets/fonts/Nunito-Medium.ttf
        weight: 500
      - asset: assets/fonts/Nunito-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Nunito-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Nunito-Bold.ttf
        weight: 800
